#!/usr/bin/env python3

"""CUrrency.py:exchange your money to another currency

__author__ = "Li Yichen"
__pkuid__  = "1800011849"
__email__  = "1800011849@pku.edu.cn"
"""
from urllib.request import urlopen
def exchange(currency_from,currency_to,amount_from):#查询的函数
    doc = urlopen('http://cs1110.cs.cornell.edu/2016fa/a1server.php?from='+currency_from+'&to='+currency_to+'&amt='+amount_from)
    docstr = doc.read()
    doc.close()
    jstr = docstr.decode('ascii')
    return jstr#返回从网页上获得的信息（字符串）

def slice(q):#将字符串切片，并表示成字典的形式
    q=q.split('"')
    a={}
    a[q[5]]=q[7]
    a[q[9]]=q[10]
    a[q[11]]=q[13]
    return a
def printf(x,y,z):#总函数，可以直接输出
    b=slice(exchange(x,y,z))
    if b['success']==' : true, ':#判断用户是否输入有误
        return b['to']
    else:
        return ('error:'+b['error'])#如果输入有误，那么报错
def test():#测试函数
    assert exchange('USD','EUR','10')=='{ "from" : "10 United States Dollars", "to" : "8.63569 Euros", "success" : true, "error" : "" }'#测试从网页获得的信息是否正确
    assert slice(exchange('USD','EUR','10'))=={'to':'8.63569 Euros','success':' : true, ','error':''}#测试对字符串的处理是否正确
    assert printf('USD','EUR','10')=='8.63569 Euros'#测试输出结果是否正确
    print('测试通过')
def main():
    test()
    x=input('currency_from:')#输入本来的货币
    y=input('currency_to:')#输入期望货币
    z=input('amount_from:')#输入钱数
    print(printf(x,y,z))
if __name__ == '__main__':
    main()


